"""second migration

Revision ID: 0ebbef7d5bc5
Revises: a8bb5a2cd1d9
Create Date: 2025-04-17 00:53:28.409084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebbef7d5bc5'
down_revision: Union[str, None] = 'a8bb5a2cd1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('copies_available', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'copies_available')
    # ### end Alembic commands ###
